###########################################################################################################
#
# This workflow creates a draft release into GitHub's releases section.
#
# It is automatically started, when a "Version: x.y.z" PR is merged.
# Its progress is commented at the "Version: x.y.z" PR.
#
# The workflow can also be started manually, if necessary.
#
# When the workflow is finished, one must visit https://github.com/syslog-ng/syslog-ng/releases,
# double check the generated draft release, and manually release it.
#
###########################################################################################################

name: Draft release


on:
  workflow_dispatch:
  pull_request:
    types: [closed]


env:
  GITHUB_TOKEN: ${{ secrets.PAT_FOR_ACTIONS }}
  WORKFLOW_NAME: "**Draft release** workflow"
  CURRENT_WORKFLOW_RUN_URL: https://github.com/${{ github.repository_owner }}/syslog-ng/actions/runs/${{ github.run_id }}
  RELEASES_URL: https://github.com/${{ github.repository_owner }}/syslog-ng/releases


jobs:
  create-release-tarball:
    runs-on: ubuntu-latest
    if: (github.event_name == 'workflow_dispatch') ||
        (github.event.pull_request.merged && contains(github.event.pull_request.labels.*.name, 'version-bump'))
    outputs:
      RELEASE_TAG: ${{ steps.setup-environment.outputs.RELEASE_TAG }}
      RELEASE_NAME: ${{ steps.setup-environment.outputs.RELEASE_NAME }}
      TARBALL_NAME: ${{ steps.setup-environment.outputs.TARBALL_NAME }}
    steps:
      - name: Checkout syslog-ng source
        uses: actions/checkout@v3

      - name: "Comment: job started"
        if: github.event_name == 'pull_request'
        run: |
          COMMENT="${WORKFLOW_NAME} started: ${CURRENT_WORKFLOW_RUN_URL}."

          gh pr comment \
            "${{ github.event.number }}" \
            --body "${COMMENT}"

      - name: Setup environment
        id: setup-environment
        run: |
          . .github/workflows/gh-tools.sh

          VERSION=`cat VERSION.txt`
          RELEASE_TAG=syslog-ng-$VERSION
          RELEASE_NAME=${RELEASE_TAG}
          TARBALL_NAME=${RELEASE_NAME}.tar.gz
          TARBALL_PATH=dbld/release/${VERSION}/${TARBALL_NAME}

          gh_export VERSION RELEASE_TAG TARBALL_PATH
          gh_output RELEASE_TAG RELEASE_NAME TARBALL_NAME

      - name: "DBLD: release"
        run: |
          ./dbld/rules release VERSION=${VERSION}

      - name: Store release tarball as artifact
        uses: actions/upload-artifact@v3
        with:
          name: release-tarball
          path: ${{ env.TARBALL_PATH }}
          if-no-files-found: error